### ISSUE TITLE
Guardian Apply job fails when the message body is too long

### ISSUE THREAD

**Issue by llarco** [abcxyz/guardian#531]
### TL;DR

`Apply Terraform` succeeded, but then it showed a failure due to the message being too long, causing the GH action step to be marked as failed, and skipping the next steps (Post Mint Token, and anything after).

```
Run guardian apply \
Starting Guardian apply
Downloading Guardian plan file
Writing plan file to disk
Creating start comment
Running Terraform commands
Initializing Terraform
Validating Terraform
Applying Terraform
Formatting output
Updating result comment
Deleting Guardian plan file
failed to write result comment: failed to create apply comment: failed to update pull request comment: failed to execute retriable function: failed to update pull request comment: PATCH https://api.github.com/repos/taara-co/gcp-org/issues/comments/2814581792: 422 Validation Failed [{Resource:IssueComment Field:body Code:custom Message:body is too long (maximum is 655[36](https://github.com/taara-co/gcp-org/actions/runs/14530265125/job/40768754066#step:9:37) characters)}]
```

### Environment Details

```markdown
Current runner version: '2.323.0'
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250413.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250413.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250413.1
Runner Image Provisioner
  2.0.422.1
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  PullRequests: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' (SHA:6fc4af4b145ae7821d527454aa9bd537d1f2dc5f)
Download action repository 'abcxyz/github-token-minter@3d06f6c61a3a3b28fc241a5105ee484c3c529f5f' (SHA:3d06f6c61a3a3b28fc241a5105ee484c3c529f5f)
Download action repository 'abcxyz/secure-setup-terraform@7f93ab7480b59d0b9c03d7128402eb7e19148b4d' (SHA:7f93ab7480b59d0b9c03d7128402eb7e19148b4d)
Download action repository 'abcxyz/pkg@3fe0963bdeae890e770c33f2bb30cfcfb5229b41' (SHA:3fe0963bdeae890e770c33f2bb30cfcfb5229b41)
Getting action download info
Download action repository 'hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8' (SHA:651471c36a6092792c552e8b1bef71e592b462d8)
Getting action download info
Download action repository 'actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57' (SHA:1bd1e32a3bdc45362d1e726936510720a7c30a57)
```

**Comment by gjonathanhong** [comment]
Can you provide the Guardian version?

**Comment by llarco** [comment]
> Can you provide the Guardian version?

```
env:
  GUARDIAN_VERSION: '1.0.3'
```

**Comment by gjonathanhong** [comment]
This should have been addressed in https://github.com/abcxyz/guardian/pull/265. I would recommend trying `GUARDIAN_VERSION: '1.0.10' to consume the fix.

**Comment by AshrafK17** [comment]
I have consumed the fix by bumping up to `GUARDIAN_VERSION: '1.0.10'`. The issue still seems to persist

```
Run guardian apply \
Starting Guardian apply
Downloading Guardian plan file
Writing plan file to disk
Creating start comment
Running Terraform commands
Initializing Terraform
Validating Terraform
Applying Terraform
Formatting output
Updating result comment
Deleting Guardian plan file
failed to write result comment: failed to create apply comment: failed to update pull request comment: failed to execute retriable function: failed to update pull request comment: PATCH https://api.github.com/repos/tidaltech/koi-infra/issues/comments/5449104969: 422 Validation Failed [{Resource:IssueComment Field:body Code:custom Message:body is too long (maximum is 65536 characters)}]
Error: Process completed with exit code 1.
```
